import type { Service } from "./types";

export const CAMPUS_CENTER: [number, number] = [33.5843, -101.8748];

export const SERVICES: Service[] = [
  {
    id: "math-midterms",
    provider: {
      name: "Maya Chen",
      initials: "MC",
      verified: true,
      rating: 4.9,
      ratingCount: 42,
      completed: 57,
      responseMinutes: 4,
    },
    title: "Calculus rescue session",
    description:
      "One focused hour for limits, derivatives, or the problem set you are stuck on.",
    category: "Tutoring",
    price: "$18 / hour",
    availability: "Free after 4:30 PM",
    distanceMiles: 0.3,
    approximatePosition: [33.5854, -101.8782],
    accent: "#f6b73c",
    tags: ["Calculus", "In person", "ENGR"],
  },
  {
    id: "laptop-repair",
    provider: {
      name: "Jordan Blake",
      initials: "JB",
      verified: true,
      rating: 4.8,
      ratingCount: 31,
      completed: 46,
      responseMinutes: 7,
    },
    title: "Laptop tune-up & setup",
    description:
      "Slow laptop, dev environment, or software setup. I will diagnose it with you.",
    category: "Tech help",
    price: "$15 flat",
    availability: "Available now",
    distanceMiles: 0.5,
    approximatePosition: [33.5811, -101.8721],
    accent: "#1d7a67",
    tags: ["Windows", "macOS", "Fast reply"],
  },
  {
    id: "airport-ride",
    provider: {
      name: "Noah Williams",
      initials: "NW",
      verified: true,
      rating: 4.7,
      ratingCount: 19,
      completed: 34,
      responseMinutes: 11,
    },
    title: "Airport ride this evening",
    description:
      "Two open seats to LBB. Split gas in person and confirm the pickup in chat.",
    category: "Ride",
    price: "$9 suggested",
    availability: "Leaves at 7:15 PM",
    distanceMiles: 0.8,
    approximatePosition: [33.5892, -101.8689],
    accent: "#cd5c45",
    tags: ["LBB", "2 seats", "Tonight"],
  },
  {
    id: "portrait-session",
    provider: {
      name: "Ari Patel",
      initials: "AP",
      verified: true,
      rating: 5,
      ratingCount: 12,
      completed: 16,
      responseMinutes: 18,
    },
    title: "Graduation portraits",
    description:
      "A relaxed 25-minute campus shoot with ten edited photos delivered tomorrow.",
    category: "Creative",
    price: "$30 session",
    availability: "Saturday morning",
    distanceMiles: 1.1,
    approximatePosition: [33.579, -101.8824],
    accent: "#7557a8",
    tags: ["Portrait", "10 edits", "Next day"],
  },
  {
    id: "move-desk",
    provider: {
      name: "Elena Ruiz",
      initials: "ER",
      verified: true,
      rating: 4.6,
      ratingCount: 8,
      completed: 13,
      responseMinutes: 6,
    },
    title: "Help moving a desk",
    description:
      "I have a pickup and straps. Best for a quick apartment-to-campus move.",
    category: "Moving",
    price: "$20 suggested",
    availability: "Tomorrow after 2 PM",
    distanceMiles: 1.4,
    approximatePosition: [33.5769, -101.8667],
    accent: "#3473a8",
    tags: ["Pickup", "Straps", "Tomorrow"],
  },
];
