import type { Service } from "./types";
import { categoryAccent } from "./service-taxonomy";

export const CAMPUS_CENTER: [number, number] = [33.5843, -101.8748];

export const SERVICES: Service[] = [
  {
    id: "social-tacos",
    provider: { name: "Nia Brooks", initials: "NB", verified: true, rating: 4.8, ratingCount: 24, completed: 31, responseMinutes: 5 },
    title: "I need company for a library break",
    description: "A small, low-key group is walking over after the study block. Join without planning a whole week ahead.",
    category: "Social", subcategory: "Grab food", listingKind: "temporary",
    price: "Split your own order", availability: "Today at 7:15 PM", distanceMiles: 0.2,
    approximatePosition: [33.5859, -101.8758], accent: categoryAccent("Social"),
    tags: ["4 going", "Casual", "Tonight"],
  },
  {
    id: "service-furniture",
    provider: { name: "Elena Ruiz", initials: "ER", verified: true, rating: 4.7, ratingCount: 18, completed: 27, responseMinutes: 6 },
    title: "I need help assembling furniture",
    description: "Flat-pack desk, shelf, or chair assembly with basic tools. We agree on scope before meeting.",
    category: "Services", subcategory: "Furniture assembly", listingKind: "temporary",
    price: "$20 suggested", availability: "Tomorrow after 2 PM", distanceMiles: 0.8,
    approximatePosition: [33.5796, -101.8717], accent: categoryAccent("Services"),
    tags: ["Tools included", "One task", "Tomorrow"],
  },
  {
    id: "math-midterms",
    provider: { name: "Maya Chen", initials: "MC", verified: true, rating: 4.9, ratingCount: 42, completed: 57, responseMinutes: 4 },
    title: "I need help with calculus",
    description: "One focused hour for limits, derivatives, or the problem set you are stuck on.",
    category: "Tutoring", subcategory: "Exam prep", listingKind: "temporary",
    price: "$18 / hour", availability: "Free after 4:30 PM", distanceMiles: 0.3,
    approximatePosition: [33.5854, -101.8782], accent: categoryAccent("Tutoring"),
    tags: ["Calculus", "In person", "ENGR"],
  },
  {
    id: "event-crew",
    provider: { name: "Campus Events Team", initials: "CE", verified: true, rating: 4.8, ratingCount: 11, completed: 19, responseMinutes: 12 },
    title: "I need three helpers for Saturday setup",
    description: "Two-hour paid shift moving lightweight signs, checking tables, and helping guests find the entrance.",
    category: "Jobs", subcategory: "Event staffing", listingKind: "temporary",
    price: "$32 total", availability: "Saturday · 3–5 PM", distanceMiles: 0.5,
    approximatePosition: [33.5827, -101.8769], accent: categoryAccent("Jobs"),
    tags: ["3 spots", "Paid", "2 hours"],
  },
  {
    id: "food-drive",
    provider: { name: "Avery Cole", initials: "AC", verified: true, rating: 4.9, ratingCount: 15, completed: 22, responseMinutes: 9 },
    title: "I need volunteers for a food drive",
    description: "Help sort shelf-stable donations into boxes. Come for thirty minutes or stay for the full session.",
    category: "Volunteer", subcategory: "Donation drives", listingKind: "temporary",
    price: "Volunteer", availability: "Saturday morning", distanceMiles: 0.7,
    approximatePosition: [33.5882, -101.8713], accent: categoryAccent("Volunteer"),
    tags: ["Drop in", "Community", "Indoors"],
  },
  {
    id: "chess-table",
    provider: { name: "Owen Price", initials: "OP", verified: true, rating: 4.6, ratingCount: 9, completed: 14, responseMinutes: 8 },
    title: "I need a beginner chess partner",
    description: "Friendly rapid games and openings for people who know the rules but want more practice.",
    category: "Clubs", subcategory: "Chess", listingKind: "temporary",
    price: "Free", availability: "Today at 6 PM", distanceMiles: 0.4,
    approximatePosition: [33.5831, -101.8791], accent: categoryAccent("Clubs"),
    tags: ["Beginners", "Boards ready", "6 PM"],
  },
  {
    id: "sunset-run",
    provider: { name: "Sam Taylor", initials: "ST", verified: true, rating: 4.8, ratingCount: 21, completed: 33, responseMinutes: 5 },
    title: "I need a running buddy",
    description: "A conversational two-mile loop. No pace pressure and nobody gets left behind.",
    category: "Activities", subcategory: "Running", listingKind: "temporary",
    price: "Free", availability: "This evening at 6:30", distanceMiles: 0.6,
    approximatePosition: [33.5872, -101.8802], accent: categoryAccent("Activities"),
    tags: ["2 miles", "Easy pace", "Outdoor"],
  },
  {
    id: "open-mic",
    provider: { name: "Jordan Blake", initials: "JB", verified: true, rating: 4.7, ratingCount: 17, completed: 29, responseMinutes: 11 },
    title: "I need performers for open-mic night",
    description: "Music, poems, and short comedy sets. Watch, perform, or bring a friend.",
    category: "Events", subcategory: "Open mics", listingKind: "temporary",
    price: "Free entry", availability: "Friday at 8 PM", distanceMiles: 0.9,
    approximatePosition: [33.5817, -101.8688], accent: categoryAccent("Events"),
    tags: ["All students", "Sign-up at 7:30", "Friday"],
  },
  {
    id: "corner-cup",
    provider: { name: "Corner Cup Coffee", initials: "CC", verified: true, rating: 4.8, ratingCount: 86, completed: 0, responseMinutes: 20 },
    title: "Coffee, snacks, and study tables",
    description: "A permanent campus-area listing with current hours, menu highlights, and student offers.",
    category: "Businesses", subcategory: "Coffee & snacks", listingKind: "permanent", sponsored: true,
    price: "$", availability: "Open today until 9 PM", distanceMiles: 1.2,
    approximatePosition: [33.5763, -101.8808], accent: categoryAccent("Businesses"),
    tags: ["Sponsored", "Permanent pin", "Student offer"],
  },
  {
    id: "west-hall-bikes",
    provider: { name: "West Hall Bike Repair", initials: "WB", verified: true, rating: 4.7, ratingCount: 38, completed: 0, responseMinutes: 15 },
    title: "Same-day bike repair",
    description: "A reviewed permanent listing for tune-ups, flat fixes, and basic parts near campus.",
    category: "Businesses", subcategory: "Professional services", listingKind: "permanent", sponsored: true,
    price: "Quotes in person", availability: "Open weekdays", distanceMiles: 1.6,
    approximatePosition: [33.5901, -101.8659], accent: categoryAccent("Businesses"),
    tags: ["Sponsored", "Permanent pin", "Reviewed"],
  },
  {
    id: "usb-c-charger",
    provider: { name: "Noah Williams", initials: "NW", verified: true, rating: 4.9, ratingCount: 12, completed: 18, responseMinutes: 3 },
    title: "I need a USB-C charger for an hour",
    description: "I am studying nearby and can lend a 65W charger while you finish your work.",
    category: "Help", subcategory: "Borrow an item", listingKind: "temporary",
    price: "Free", availability: "Available now", distanceMiles: 0.1,
    approximatePosition: [33.5846, -101.8732], accent: categoryAccent("Help"),
    tags: ["65W", "Borrow", "Nearby"],
  },
];
